"""Notebook_Final_Sprint5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uzrZKR2USFaiXyBvjEI-6VFs1ZAG3eRf

#  🔷 **Projeto Grupo BT-G3**

<center><img src="https://cdn.discordapp.com/attachments/937463646181785633/1100078873422602350/BTG3_1.png" width="50%" height="30%"/></center>

## 🚀 **Integrantes do grupo**
- Daniel Barzilai
- Larissa Carvalho
- Maria Luisa Maia
- Pedro Rezende
- Rafael Moritz
- Vitor Oliveira

<center><img src="https://www.inteli.edu.br/wp-content/uploads/2021/08/20172028/marca_1-2.png" width="50%" height="30%"/></center>

<h1 align='center'><b>IA para Marketing: Monitoramento de campanhas utilizando processamento de linguagem natural (PLN)<b></h1>

<center><img src="https://upload.wikimedia.org/wikipedia/commons/c/c2/Btg-logo-blue.svg" width="50%" height="50%"/></center>

<h2 align='center'>O Banco BTG Pactual enfrenta um desafio na área de Marketing em entender as necessidades e demandas dos clientes de maneira fácil e rápida nas redes sociais.</h2>

<h2 align='center'>A solução proposta para esse problema foi o desenvolvimento de uma Inteligência Artificial utilizando processamento de linguagem natural (PLN), capaz de monitorar os sentimentos das campanhas de marketing, voltadas para o Instagram. </h2>

<h2 align='center'> O objetivo principal dessa solução é acatar os dados, analisar e interpretar as mensagens e comentários enviados pelos clientes na rede social, a fim de identificar as necessidades e demandas de forma precisa e eficiente, a partir do sentimento exposto dentro daquela campanha.</h2>

# ❗ **Sobre os dados**

Esse projeto está utilizando dados coletados e tratados pela equipe de Automation do banco BTG Pactual, o qual disponibilizou o dataset.

Com base nas informações dispostas nesse dataset, realizamos insights a cerca dos comentários feitos nos posts do Instagram do próprio banco. Vale lembrar que os dados estão anonimizados e resguardados para manter a privacidade e ética com os usuários e com o banco.

Agradecemos a compreensão 🤓

# 💻 **Sobre o notebook**

O projeto foi realizado através do Google Colaboratory / Jupyter Notebook (arquivo IPYNB). Nas sessões seguintes iremos demonstrar um passo a passo de como os dados foram manejados até chegar em uma conclusão e na entrega do modelo. As sessões estão estruturadas da seguinte forma:

1. Setup do notebook;
2. Exploratória dos dados;
3. Criação de features;
4. Pré-processos dos dados;
5. Modelo de Vetorização;
5. Construção do Modelo;
6. Interpretação e Avaliação do modelo;

**OBS**: O notebook foi desenvolvido com foco em funções, para que fosse possível fazer a substituição de qualquer variável e obter o resultado a partir de uma nova base.

# ⏰ Principais mudanças da última Sprint

1. Fizemos a escolha de proceder com o processo de vetorização Word2Vec
2. Escolhemos o algoritmo Random Forest como principal
3. Desenvolvemos este notebook para apresentar como notebook final
4. Desenvolvemos o serviço de mostragem do que foi desenvolvido, a partir da ferramenta Streamlit (está em uma pasta do GitHub)
5. Refinamos os hiperparâmetros do modelo para buscar um melhor valor de recall. No final, tivemos um modelo de 81% de recall voltado para os negativos, que era o nosso objetivo.

# 1. 🔧 Setup - Instalações

A configuração do setup é o ato de preparar e arrumar o ambiente de maneira apropriada para ser utilizado. Isso inclui a instalação de bibliotecas e a realização de ajustes necessários.

O propósito é criar um ambiente operacional no qual seja possível realizar tarefas específicas com eficiência.

## 1.1 Conexão com o Google Drive (se necessário)
"""

#Conectar com o Google Drive - Para casos de uso do Google Colaboratory

from google.colab import drive
drive.mount('/content/drive')

"""## 1.2 Instalação e Importação de bibliotecas"""

!pip install unidecode

!pip install emoji

!pip install -U spacy
!python -m spacy download pt_core_news_sm

!pip install nltk

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from wordcloud import WordCloud
import re
import unidecode
import seaborn as sns
from collections import Counter

import emoji
import spacy
import nltk

nltk.download('punkt')
from nltk import tokenize
from nltk.tokenize import TweetTokenizer
from nltk import word_tokenize, pos_tag

nltk.download('stopwords')
from nltk.corpus import stopwords

nltk.download('rslp')
from nltk.tokenize import RegexpTokenizer

nltk.download('wordnet')
from nltk.stem.snowball import SnowballStemmer
from nltk.corpus import PlaintextCorpusReader
from nltk.stem import WordNetLemmatizer

from sklearn.feature_extraction.text import CountVectorizer
from keras.preprocessing.text import Tokenizer
from sklearn import preprocessing
from sklearn import metrics
from sklearn.metrics import accuracy_score, ConfusionMatrixDisplay, classification_report, confusion_matrix, f1_score, recall_score
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.utils import resample

import gensim
from scipy.spatial.distance import cosine
from gensim.models import KeyedVectors, Word2Vec

import pickle

"""# 2. 🌎 Exploratória dos dados

## 2.1 Leitura e visualização do CSV

- Explicar o porque de eu estar tirando a coluna autor
"""

df = pd.read_csv('/content/drive/MyDrive/Módulo 6/projeto/Bases/base_nova_csv.csv')
df_original = df.drop(columns=['"autor"'])
df_original

df_original.columns

df_original.dtypes

"""## 2.2 Tratamento da base

### 2.2.1 Retirada de " " (aspas) das colunas
"""

def tiraAspas(base):
    df = base.rename(columns=lambda x: re.sub('[\"\']', '', x))
    return df

df_tratada = tiraAspas(df_original)
df_tratada

df_tratada['sentimento'].value_counts()

df_tratada['tipoInteracao'].value_counts()

df_tratada['anomalia'].value_counts()

df_tratada['contemHyperlink'].value_counts()

df_tratada['processado'].value_counts()

"""### 2.2.2 Drop nas linhas com **Anomalia**

- Explicar o que é Anomalia e as outras colunas que influenciam nela
"""

df_sem_anomalia = df_tratada[df_tratada['anomalia'] != 1]
df_sem_anomalia

"""### 2.2.3 Drop nas colunas que não nos servem"""

df_dropado = df_sem_anomalia.drop(['id', 'dataPublicada', 'anomalia', 'probabilidadeAnomalia', 'linkPost', 'processado', 'contemHyperlink'], axis=1)
df_dropado

df_tratada['sentimento'].value_counts()

df = df_dropado.reset_index(drop=True)
df

"""## 2.3 Plotando Gráficos

#### Os tipos de interações mais frequentes
"""

# Contar os tipos de interação
count_interactions = df['tipoInteracao'].value_counts()
# Criar o gráfico de pizza
plt.figure(figsize=(8, 6))
count_interactions.plot(kind='pie', autopct='%1.1f%%')
plt.title('Tipos de Interação')
plt.ylabel('')
plt.show()

"""#### Tipos de sentimentos mais frequentes"""

# Contar os tipos de sentimentos
count_sentimentos = df['sentimento'].value_counts()

# Plotagem do gráfico de barras
plt.figure(figsize=(10, 6))
count_sentimentos.plot(kind='bar')
plt.xlabel('Sentimentos')
plt.ylabel('Contagem')
plt.title('Tipos de Sentimento')
plt.show()

"""#### Frequência dos sentimentos por tipo de Interação"""

# Contar os tipos de sentimentos por Interação
contagem = df.groupby(['tipoInteracao', 'sentimento']).size().unstack(fill_value=0)

# Plotagem do gráfico de barras
plt.figure(figsize=(10, 6))
contagem.plot(kind='bar', stacked=True)
plt.xlabel('Sentimentos por Interação')
plt.ylabel('Contagem')
plt.title('Tipos de Sentimento')
plt.show()

"""# 3. 🔍 Criação de features

- Nesta seção iremos criar as features que irão ajudar o nosso modelo a analisar novas frases e descobrir o sentimento por trás delas.
- Essas features serão uma lista de emojis feita a mão por nós!
- A lista pode ser modificada, tanto em sua quantidade, quanto em seus valores textuais.
"""

df

"""## 3.1 Emojis presentes no dataset"""

# Cria um conjunto vazio para armazenar os emojis encontrados
emojis_encontrados = set()

# Define uma expressão regular para encontrar emojis
emoji_pattern = re.compile("["
                           u"\U0001F600-\U0001F64F"  # emoticons
                           u"\U0001F300-\U0001F5FF"  # símbolos e pictogramas
                           u"\U0001F680-\U0001F6FF"  # transporte e símbolos de mapas
                           u"\U0001F1E0-\U0001F1FF"  # bandeiras do mundo
                           u"\U00002702-\U000027B0"
                           u"\U000024C2-\U0001F251"
                           "]+", flags=re.UNICODE)

# Itera sobre cada linha do dataframe e extrai os emojis da coluna 'texto'
for text in df['texto']:
    emojis_encontrados.update(set(emoji_pattern.findall(text)))

# Converte o conjunto de emojis encontrados em uma lista
lista_de_emojis = list(emojis_encontrados)

# Cria uma lista vazia para armazenar os emojis separados
emojis_separados = []

# Itera sobre a lista de emojis e adiciona cada caracter a uma nova lista
for emoji in lista_de_emojis:
    emojis_separados.extend(list(emoji))

# Exibe a lista de emojis separados
print('Lista de emojis separados:')
print(emojis_separados)

# Conta a frequência de cada emoji na lista de emojis separados
frequencia_de_emojis = Counter(emojis_separados)

# Exibe a frequência de cada emoji
print('Frequência de cada emoji:')
for emoji, frequencia in frequencia_de_emojis.items():
    print(f'{emoji}: {frequencia}')

"""## 3.2 Frequência dos emojis"""

def frequencia(input):
    emojis = frequencia_de_emojis
    dfCount = pd.DataFrame(list(emojis.items())) # transformando em dataframe para melhor visualização
    dfCount.rename(columns={0: "Emoji", 1:"Frequência"}, inplace=True) # renomeando as colunas
    final_df = dfCount.sort_values(by=['Frequência'], ascending=False) # ordenando o dataframe
    return final_df

output = frequencia(df['texto'])
output.head(10)

"""## 3.3 Criação das colunas/features com valor textual dos emojis

"""

emoji_dict = {
    '😄': 'sorriso',
    '😆': 'risos',
    '😊': 'envergonhado',
    '😃': 'sorridente',
    '😏': 'sorriso',
    '😍': 'olhos_coracao',
    '😘': 'beijo_coracao',
    '😚': 'beijo_olhos_fechados',
    '😳': 'corado',
    '😌': 'aliviado',
    '😉': 'satisfeito',
    '😁': 'sorrisao',
    '😜': 'piscadela',
    '😝': 'lingua_fora_olhos_fechados',
    '😀': 'rindo_muito',
    '😗': 'beijo',
    '😙': 'beijo_sorriso_olhos',
    '😛': 'lingua_fora',
    '😴': 'dormindo',
    '😟': 'preocupado',
    '😦': 'franzindo_testa',
    '😧': 'angustiado',
    '😮': 'boca_aberta',
    '😬': 'careta',
    '😕': 'confuso',
    '😯': 'silencioso',
    '😑': 'expressão_neutra',
    '😒': 'desinteressado',
    '😅': 'sorriso_suado',
    '😔': 'desapontado',
    '😨': 'amedrontado',
    '😰': 'suando_frio',
    '😣': 'perseverando',
    '😢': 'choro',
    '😭': 'choro',
    '😂': 'alegria',
    '😲': 'surpreso',
    '🤓': 'nerd',
    '😫': 'cansado',
    '😠': 'raiva',
    '😡': 'raiva_intensa',
    '😤': 'bufada',
    '😋': 'delicioso',
    '😷': 'mascara',
    '😎': 'oculos_escuros',
    '😵': 'morte',
    '👿': 'diabinho',
    '😈': 'diabinho',
    '😶': 'sem_boca',
    '💙': 'coração',
    '✨': 'brilho',
    '🌟': 'estrela brilhante',
    '💥': 'explosao',
    '❗': 'exclamacao',
    '❓': 'interrogacao',
    '💤': 'sono',
    '🔥': 'fogo',
    '💩': 'cocô',
    '👌': 'ok',
    '👊': 'soquinho',
    '👋': 'aceno',
    '🙌': 'maos_ceu',
    '🙏': 'rezando',
    '👏': 'palmas',
    '💪': 'força',
    '🖕': 'dedo_meio',
    '👉': 'apontando_direita',
    '🙈': 'vergonha',
    '💋': 'beijo',
    '🎉': 'celebração',
    '🎊': 'confete',
    '📞': 'telefone',
    '📣': 'anuncio',
    '⌛': 'tempo_acabando',
    '⏰': 'alarme',
    '💰': 'grana',
    '💣': 'bomba',
    '📈': 'gráfico_subindo',
    '📉': 'gráfico_descendo',
    '📅': 'calendário',
    '🏦': 'banco',
    '🚀': 'foguete',
    '🚨': 'sirene',
    '🔝': 'top',
    '🆙': 'up',
    '🆘': 'socorro',
    '🔞': 'proibido_menores_idade',
    '🔜': 'breve',
    '❌': 'erro',
    '💯': 'perfeição',
    '✅': 'aprovado',
    '⤵️': 'seta_para_baixo_esquerda',
    '⚠️': 'atenção',
    '🤯': 'cabeça_explodindo',
    '💸': 'dinheiro',
    '📍': 'localização',
    '💕': 'localização',
    '🍀': "trevo",
    '🏆': "trofeu" ,
    '💖': "coracao_pixel" ,
    '👽': "alien" ,
    '🎯': "alvo",
    '📊': "grafico_barra",
    '👎': "ruim",
    '😐': "entediado",
    '😇': "anjo" ,
    '👼': "anjo",
    '💵': "dinheiro",
    '💴': "dinheiro",
    '💳': "cartao",
    '💻': "computador",
    '📷': "camera",
    '👍': "bom",
    '😞': "decepcao",
    '💚': "coracao",
    '🚫': "bloqueado",
    '💲': "dinheiro",
    '🌹': "flor",
    '👀': "olhos",
    '👈': "mao_esquerda",
    '💓': "coracao",
    '💜': "coracao",
    '🙃': "cara_baixo",
    '👻': "fantasma",
    '👇': "dedo_baixo",
    '😱': "assustado",
    '😩': "nervoso",
    '💛': "coracao",
    '😻': "apaixonado",
    '😺': "feliz",
    '🤒': "doente"
}

len(emoji_dict)

# Função para verificar a existência de cada emoji no texto
def verifica_emoji(texto, emoji):
    if emoji in texto:
        return 1
    else:
        return 0

# Adiciona uma coluna para cada emoji no DataFrame
for emoji, descricao in emoji_dict.items():
    df[descricao] = df['texto'].apply(lambda x: verifica_emoji(x, emoji))

# Exibe o DataFrame resultante
df

df['palmas'].value_counts()

"""# 4. ⌛ Pré-Processamento dos dados

Aqui em Pré-processamento, faremos a definição de diversas funções referentes aos tratamentos que mostramos acima!

Assim, nosso objetivo aqui é simplificar os as frases, separando em palavras, alterando o valor semântico, tratando abreviações, etc., com o objetivo de fazer as frases mais simplórias e deixar a vetorização mais "assertiva", resultando numa melhor análise do modelo.

essa é a lista de tratamentos que iremos fazer em nosso *corpus*:

1. Tokenização
2. Tratamento de emojis
3. Remoção de Alfanuméricos
4. Tratamento de abreviações
5. Remoção de Stopwords
6. Lematização

- Retirando a coluna de 'TipoInteracao' pois não iremos usar mais
"""

df = df.drop(['tipoInteracao'], axis=1)
df

"""## 4.1 Criação das Funções

### 4.1.1 Tokenização
"""

def tokenizer(comentarios):
  comentarios_tokenizados = []
  tk = TweetTokenizer()
  for comentario in comentarios:
    palavras = tk.tokenize(comentario.lower())
    comentarios_tokenizados.append(palavras)
  return comentarios_tokenizados

"""### 4.1.2 Tratamento de emojis"""

emoji_dict = {
    '😄': 'sorriso',
    '😆': 'risos',
    '😊': 'envergonhado',
    '😃': 'sorridente',
    '😏': 'sorriso',
    '😍': 'olhos_coracao',
    '😘': 'beijo_coracao',
    '😚': 'beijo_olhos_fechados',
    '😳': 'corado',
    '😌': 'aliviado',
    '😉': 'satisfeito',
    '😁': 'sorrisao',
    '😜': 'piscadela',
    '😝': 'lingua_fora_olhos_fechados',
    '😀': 'rindo_muito',
    '😗': 'beijo',
    '😙': 'beijo_sorriso_olhos',
    '😛': 'lingua_fora',
    '😴': 'dormindo',
    '😟': 'preocupado',
    '😦': 'franzindo_testa',
    '😧': 'angustiado',
    '😮': 'boca_aberta',
    '😬': 'careta',
    '😕': 'confuso',
    '😯': 'silencioso',
    '😑': 'expressão_neutra',
    '😒': 'desinteressado',
    '😅': 'sorriso_suado',
    '😔': 'desapontado',
    '😨': 'amedrontado',
    '😰': 'suando_frio',
    '😣': 'perseverando',
    '😢': 'choro',
    '😭': 'choro',
    '😂': 'alegria',
    '😲': 'surpreso',
    '🤓': 'nerd',
    '😫': 'cansado',
    '😠': 'raiva',
    '😡': 'raiva_intensa',
    '😤': 'bufada',
    '😋': 'delicioso',
    '😷': 'mascara',
    '😎': 'oculos_escuros',
    '😵': 'morte',
    '👿': 'diabinho',
    '😈': 'diabinho',
    '😶': 'sem_boca',
    '💙': 'coração',
    '✨': 'brilho',
    '🌟': 'estrela brilhante',
    '💥': 'explosao',
    '❗': 'exclamacao',
    '❓': 'interrogacao',
    '💤': 'sono',
    '🔥': 'fogo',
    '💩': 'cocô',
    '👌': 'ok',
    '👊': 'soquinho',
    '👋': 'aceno',
    '🙌': 'maos_ceu',
    '🙏': 'rezando',
    '👏': 'palmas',
    '💪': 'força',
    '🖕': 'dedo_meio',
    '👉': 'apontando_direita',
    '🙈': 'vergonha',
    '💋': 'beijo',
    '🎉': 'celebração',
    '🎊': 'confete',
    '📞': 'telefone',
    '📣': 'anuncio',
    '⌛': 'tempo_acabando',
    '⏰': 'alarme',
    '💰': 'grana',
    '💣': 'bomba',
    '📈': 'gráfico_subindo',
    '📉': 'gráfico_descendo',
    '📅': 'calendário',
    '🏦': 'banco',
    '🚀': 'foguete',
    '🚨': 'sirene',
    '🔝': 'top',
    '🆙': 'up',
    '🆘': 'socorro',
    '🔞': 'proibido_menores_idade',
    '🔜': 'breve',
    '❌': 'erro',
    '💯': 'perfeição',
    '✅': 'aprovado',
    '⤵️': 'seta_para_baixo_esquerda',
    '⚠️': 'atenção',
    '🤯': 'cabeça_explodindo',
    '💸': 'dinheiro',
    '📍': 'localização',
    '💕': 'localização',
    '🍀': "trevo",
    '🏆': "trofeu" ,
    '💖': "coracao_pixel" ,
    '👽': "alien" ,
    '🎯': "alvo",
    '📊': "grafico_barra",
    '👎': "ruim",
    '😐': "entediado",
    '😇': "anjo" ,
    '👼': "anjo",
    '💵': "dinheiro",
    '💴': "dinheiro",
    '💳': "cartao",
    '💻': "computador",
    '📷': "camera",
    '👍': "bom",
    '😞': "decepcao",
    '💚': "coracao",
    '🚫': "bloqueado",
    '💲': "dinheiro",
    '🌹': "flor",
    '👀': "olhos",
    '👈': "mao_esquerda",
    '💓': "coracao",
    '💜': "coracao",
    '🙃': "cara_baixo",
    '👻': "fantasma",
    '👇': "dedo_baixo",
    '😱': "assustado",
    '😩': "nervoso",
    '💛': "coracao",
    '😻': "apaixonado",
    '😺': "feliz",
    '🤒': "doente"
}

def demojize_tokens(words, emoji_dict):
    demojized = []
    for word in words:
        if isinstance(word, list):  # Verifica se é uma lista de tokens
            processed_word = []
            for token in word:
                if emoji.emoji_count(token) > 0:
                    if token in emoji_dict:
                        processed_word.append(emoji_dict[token])
                    else:
                        processed_word.append(emoji.demojize(token))
                else:
                    processed_word.append(token)
            demojized.append(processed_word)
        else:
            if emoji.emoji_count(word) > 0:
                if word in emoji_dict:
                    demojized.append(emoji_dict[word])
                else:
                    demojized.append(emoji.demojize(word))
            else:
                demojized.append(word)

    demojized = [
        [
            token.replace(":", "").replace("_", "") if any(c in token for c in [":", "_"]) else token
            for token in sublist
        ] if isinstance(sublist, list)
        else sublist.replace("-", "_") if "-" in sublist
        else sublist
        for sublist in demojized
    ]

    return demojized

"""### 4.1.3 Tratamento ReGex"""

def removendo_alfanumericos(tokens):
  output_tokens = []
  for sentence in tokens:
      output_list = []
      for palavra in sentence:
          if palavra.strip(): # Verifica se a palavra não é uma string vazia
            palavra_sem_marcacao = re.sub((r'@\w*'), '', palavra)
            palavra_sem_hashtag = re.sub((r'#\w*'), '', palavra_sem_marcacao)
            palavra_sem_hyperlink = re.sub(r'https\S*', '', palavra_sem_hashtag)
            palavra_sem_www = re.sub(r'\bwww\.[^\s]*', '', palavra_sem_hyperlink)
            palavra_sem_numeros = re.sub((r'[0-9]'), '', palavra_sem_www)
            palavra_sem_btg = re.sub((r'\bbtg\b'), '', palavra_sem_numeros)
            palavra_sem_btgpactual = re.sub((r'\bpactual\b'), '', palavra_sem_btg)
            output_list.extend(re.findall(r'\w+', palavra_sem_btgpactual)) # analisar se não é melhor usar o append em vez de extend
      output_tokens.append(output_list)
  return output_tokens

"""### 4.1.4 Tratamento de abreviações"""

# Dicionário de gírias e abreviações para normalização
dicionario_girias = {
    'vc': 'você',
    'vcs':'você',
    'Vc': 'você',
    'pq': 'porque',
    'Pq': 'porque',
    'tbm': 'também',
    'q': 'que',
    'td': 'tudo',
    'blz': 'beleza',
    'flw': 'falou',
    'kd': 'cadê',
    'Gnt ': 'gente',
    'gnt ': 'gente',
    'to': 'estou',
    'mt': 'muito',
    'cmg': 'comigo',
    'ctz': 'certeza',
    'jah': 'já',
    'naum': 'não',
    'ta': 'está',
    'eh': 'é',
    'vdd': 'verdade',
    'vlw': 'valeu',
    'p': 'para',
    'sdds': 'saudades',
    'qnd': 'quando',
    'msm': 'mesmo',
    'fzr': 'fazer',
    's' : 'sim',
    'ss': 'sim',
    'Ss': 'sim',
    'pdc': 'pode crer',
    'n' : 'não',
    'nn': 'não',
    'Nn': 'não',
    'pls': 'please',
    'obg': 'obrigado',
    'agr': 'agora'
}

def comentarios_normalizados(tokens, dicionario_girias):
  tokens_normalizados = []

  for sentence in tokens:
    treated = []

    for palavra in sentence:
      if palavra in dicionario_girias:
          palavra_normalizada = dicionario_girias.get(palavra, palavra)
          treated.append(palavra_normalizada)
      else:
          treated.append(palavra)

    treated = [palavra.replace(' ', '') if '_' in palavra else palavra for palavra in treated]
    tokens_normalizados.append(treated)

  return tokens_normalizados

"""### 4.1.5 Remoção de Stopwords"""

stopwords = nltk.corpus.stopwords.words('portuguese')
len(stopwords)

type(stopwords)

new_stopwords = [ 'a', 'à', 'aí', 'ali', 'ante', 'ao', 'aos', 'aquela', 'aquelas', 'aquele', 'aqueles', 'as', 'às', 'cá', 'catorze', 'cento', 'cima', 'cinco', 'coisa', 'coisas', 'com', 'da', 'dá', 'daquela', 'daquelas', 'daquele', 'daqueles', 'das', 'de', 'dela', 'delas', 'dele', 'deles', 'desde', 'dessa', 'dessas', 'desse', 'desses', 'desta', 'destas', 'deste', 'destes', 'disse', 'disso', 'disto', 'do', 'dois', 'dos', 'e', 'é', 'ela', 'elas', 'ele', 'eles', 'em', 'era', 'eram', 'és', 'essa', 'essas', 'esse', 'esses', 'esta', 'estás', 'este', 'esteja', 'estejam', 'estejamos', 'estes', 'esteve', 'estive', 'estivemos', 'estiver', 'estivera', 'estiveram', 'estivéramos', 'estiverem', 'estivermos', 'estivesse', 'estivessem', 'estivéssemos', 'estiveste', 'estivestes', 'fazeis', 'fazes', 'for', 'fôramos', 'forem', 'formos', 'fôssemos', 'foste', 'hajam', 'hajamos', 'hão', 'havemos', 'havia', 'hei', 'houvemos', 'houver', 'houvera', 'houverá', 'houveram', 'houvéramos', 'houverei', 'houverem', 'houveremos', 'houveria', 'houveriam', 'houveríamos', 'houvermos', 'houvesse', 'houvessem', 'houvéssemos', 'la','lhe', 'lhes', 'lo', 'na', 'nas', 'o', 'os', 'ou', 'partir', 'paucas', 'per', 'perante', 'pôde', 'quáis', 'que', 'quereis', 'queremas', 'queres', 'sob', 'sois', 'teus', 'ti', 'tivera', 'tivéramos', 'tiverem', 'tivermos', 'tiveste', 'tivestes', 'vais', 'vossas', 'vosso', 'vossos', 'zero', '1', '2', '3', '4', '5', '6', '7', '8', '9', '0', '_' ]

len(new_stopwords)

sem_acentuacao_stopwords = ['de','a','o','que','e','do','da','em','um','e','os','dos','ele','das','a','ou','ser','ha','esta','nas','esse','suas','elas','lhe','pelas','te','vos','lhes','tua','teus','tuas','aquelas','estiveramos','hei','ha','havemos','hao','houve','houvemos','houveramos','hajamos','hajam','houvesse','houvessemos','houvessem','houver','houvermos','houverem','houverei','houvera','houveremos','houverao','houveria','houveriamos','houveriam','sao','foramos','formos','tivera','tiverem']
len(sem_acentuacao_stopwords)

def merge_stopwords(arr1, arr2):
    merged = arr1.copy()  # Cria uma cópia do primeiro array
    for element in arr2:
        if element not in merged:
            merged.append(element)  # Adiciona apenas os elementos que não estão presentes no primeiro array
    return merged

stopwords = merge_stopwords(stopwords, new_stopwords)
stopwords = merge_stopwords(stopwords, sem_acentuacao_stopwords)
stopwords.remove('não')

len(stopwords)

type(stopwords)

def remove_stopwords(tokens):
  filtered_tokens = []
  for sentence in tokens:
      filtered = [palavra for palavra in sentence if palavra not in stopwords]
      filtered_tokens.append(filtered)
  return filtered_tokens

"""### 4.1.6 Lematização"""

def lematizacao(tokens):
  # Carregar o modelo pré-treinado do SpaCy para o idioma português
  nlp = spacy.load("pt_core_news_sm")
  lemmatized_tokens = []

  for sentence in tokens:
    lemma_list = []
    doc = nlp(" ".join(sentence))  # Unir as palavras da frase em uma única string

    for token in doc:
      if token.lemma_ != '-PRON-':
        if token.pos_ == 'VERB':
          palavra_lematizada = token.lemma_
        else:
          palavra_lematizada = token.lemma_

        if palavra_lematizada:
          lemma_list.append(palavra_lematizada)

    lemmatized_tokens.append(lemma_list)

  # Converter todas as palavras para minúsculas
  lemmatized_tokens_lower = []
  for sentence in lemmatized_tokens:
    sentence_lower = [palavra.lower() for palavra in sentence]
    lemmatized_tokens_lower.append(sentence_lower)

  return lemmatized_tokens_lower

"""## 4.2 Testes das Funções

### Printando frase de exemplo, para teste
"""

print(df['texto'].iloc[92])

"""### 4.2.1 Tokenização"""

tokenized_data = tokenizer(df['texto'])
print(tokenized_data[92])

"""### 4.2.2 Tratamento de emojis
❗❗❗**AVISO IMPORTANTE**❗❗❗

Caso não funcione, volte para a seção '**1.2 Instalação e Importação de bibliotecas**' e coloque para rodar **TUDO** novamente.
"""

demojized_data = demojize_tokens(tokenized_data, emoji_dict)
print(demojized_data[92])

"""### 4.2.3 Tratamento ReGex"""

alfanumericos_data = removendo_alfanumericos(demojized_data)
print(alfanumericos_data[92])

"""### 4.2.4 Tratamento de abreviações"""

normalizacao_data = comentarios_normalizados(alfanumericos_data, dicionario_girias)
print(normalizacao_data[92])

"""### 4.2.5 Remoção de Stopwords
❗❗❗**AVISO IMPORTANTE**❗❗❗

Caso não funcione, volte para a seção '**4.1.5 Remoção de Stopwords**' e coloque para rodar **TUDO** novamente.
"""

stopwords_data = remove_stopwords(normalizacao_data)
print(stopwords_data[92])

"""### 4.2.6 Lematização"""

lematizacao_data = lematizacao(stopwords_data)
print(lematizacao_data[92])

"""## 4.3 Criando novas colunas

Nessa seção de processamento, nós aplicamos as funções criadas anteriormente e passamos elas no dataframe, como forma de demonstrar os resultados efetivos.

- tokenized = Tokenização das frases
- emojis_tratados = tratamento de emojis
- regex_tratado = tratamento ReGex
- sem_abreviacoes = Tratamento de abreviações
- no_stopwords = tratamento de stopwords
- lematizado = Lematização do conteúdo
"""

df

"""### 4.3.1 Tokenização"""

df['tokenized'] = tokenizer(df['texto'])
df.head(10)

"""### 4.3.2 Tratamento de emojis"""

df['emojis_tratados'] = demojize_tokens(df['tokenized'], emoji_dict)
df.head(10)

"""### 4.3.3 Tratamento ReGex"""

df['regex_tratado'] = removendo_alfanumericos(df['emojis_tratados'])
df.head(10)

"""### 4.3.4 Tratamento de abreviações"""

df['sem_abreviacoes'] = comentarios_normalizados(df['regex_tratado'],dicionario_girias) # tem que ver como passar como argumento o dicionário de abreviação e a lista de excluir palavras
df.head(10)

"""### 4.3.5 Remoção de Stopwords"""

df['no_stopwords'] = remove_stopwords(df['sem_abreviacoes'])
df.head(10)

"""### 4.3.6 Lematização"""

df['lematizado'] = lematizacao(df['no_stopwords'])
df

"""### 4.3.7 Organização do dataset

- Drop em linhas nulas
"""

df = df.drop(df[df['lematizado'].apply(lambda x: len(x) == 0)].index)
df

"""- Resetando o index"""

df = df.reset_index(drop=True)
df

"""- Drop em colunas que não serão mais utilizadas"""

df_organizado = df.drop(['tokenized', 'emojis_tratados', 'regex_tratado', 'sem_abreviacoes', 'no_stopwords'], axis=1)
df_organizado

"""- Mudando o nome da coluna final que foi tratada"""

df_organizado = df_organizado.rename(columns= {'lematizado': 'texto_tratado'})
df_organizado

"""- Reordenando as colunas"""

# Reordenar as colunas
cols = df_organizado.columns.tolist()
cols.insert(1, cols.pop(cols.index('texto_tratado')))
df_arrumado = df_organizado.reindex(columns=cols)
df_arrumado

"""- Fazendo um Label Enconding dos valores da coluna target"""

# Realizando o replace dos valores
replace_dict = {'POSITIVE': 2, 'NEUTRAL': 1, 'NEGATIVE': 0}
df_arrumado['sentimento'] = df_arrumado['sentimento'].replace(replace_dict)
df_arrumado

"""# 5. ☕ Pipeline do pré-processamento

- Salvando o dataset tratado com as features;
- Nesta seção, irei implementar o código para salvar o dataset como csv, caso seja preferível utilizar o dataset em outro lugar.
"""

# df_arrumado.to_csv('dataset_tratado_features', index=False)

"""

---

"""

df_arrumado

"""## 5.1 Definição da Função de Pipeline

- Função Pipeline que chama todas as outras funções
"""

def pipeline(comment):
      # Tokenização
      tokens = tokenizer(comment)
      # Tratamento de Emojis
      demojized = demojize_tokens(tokens, emoji_dict)
      # Remoção dos alfanuméricos
      no_alfanumericos = removendo_alfanumericos(tokens)
      # Normalização das abreviações
      normalizado = comentarios_normalizados(no_alfanumericos, dicionario_girias)
      # Remoção das stopwords
      no_stopwords = remove_stopwords(normalizado)
      # lematização
      tratados = lematizacao(no_stopwords)

      return tratados

"""## 5.2 Teste da Função

- Criação de uma nova coluna chamada 'pipeline' para comprovar que o output está igual ao de 'texto_tratado'
"""

df_arrumado['pipeline'] = pipeline(df['texto'])
# Reordenar as colunas
cols = df_arrumado.columns.tolist()
cols.insert(2, cols.pop(cols.index('pipeline')))
df_pipeline = df_arrumado.reindex(columns=cols)
df_pipeline

"""## 5.3 Reset do Dataframe para a forma anterior ao pipeline"""

df = df_pipeline.drop(['pipeline'], axis=1)
df

"""# 6. 📐 Vetorização

- Nesta seção iremos aplicar o processo de vetorização Word2Vec, o qual é um dos métodos estatísticos mais utilizados no pré-processamento de dados de texto a fim de uso do PLN (processamento de linguagem natural).
- O objetivo principal do Word2Vec é mapear palavras em um espaço vetorial de dimensões reduzidas, de forma que palavras semanticamente similares sejam representadas por vetores próximos. Esse algoritmo é capaz de capturar relações semânticas e sintáticas entre palavras com base em sua distribuição no corpus de treinamento.
"""

df

"""## 6.1 Definição das funções

- Treinar o algoritmo do modelo Word2Vec
"""

# Função que treina o modelo Word2Vec no corpus do dataframe
def train_word2vec(df, column_name):
    # Obtém as frases tokenizadas
    sentences = df[column_name].tolist()

    # Treina o modelo Word2Vec
    model = Word2Vec(sentences, min_count=1) # O argumento "min_count" é um parâmetro opcional que indica o número mínimo de vezes que uma palavra deve aparecer no corpus para ser considerada no treinamento.

    return model

"""- Criar a tabela de vetores e depois aplicar no dataframe, todos os vetores coletados."""

# Função que define os vetores para cada palavra do vocabulario
def get_word_vectors(model, sentence):
    vectors = []
    for word in sentence:
        if word in model.wv:
            vectors.append(model.wv[word]) # Append na lista de vetores
    if vectors:
        return np.sum(vectors, axis=0)/len(sentence) # Soma dos vetores para cada frase
    else:
        return np.zeros(model.vector_size)

# Criação do dataframe de vetores para cada frase
def create_word2vec_dataframe(df, column_name, model):
    sentences = df[column_name].tolist()
    vectors = [get_word_vectors(model, sentence) for sentence in sentences] # Itera para cada frase um vetor
    # Criação do dataframe
    df_vectors = pd.DataFrame(vectors, columns=[f"Vetor{i}" for i in range(model.vector_size)])
    df_word2vec = pd.concat([df, df_vectors], axis=1)
    return df_word2vec

"""## 6.2. Teste das funções

- Assim, foram criados 100 vetores para cada frase do index.
- Foram criadas a partir da coluna 'texto_tratado'.
"""

model = train_word2vec(df, 'texto_tratado')
df_word2vec = create_word2vec_dataframe(df,'texto_tratado', model)
df_word2vec

"""# 7. 👾 Modelo"""

df_word2vec

contagem = df_word2vec['sentimento'].value_counts()
print(contagem)

"""## 7.1 Definição da Função de criação do modelo

- Para o caso atual, estamos utilizando o algoritmo Random Forest
"""

def classification_random_forest(x, y):
  # Dividir o conjunto de dados em treinamento e teste
  x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42)

  # Criar e treinar o modelo Random Forest
  modelo_rf = RandomForestClassifier()
  modelo_rf.fit(x_train, y_train)

  # Fazer previsões no conjunto de teste
  y_pred = modelo_rf.predict(x_test)

  # Calcular a acurácia
  acuracia = accuracy_score(y_test, y_pred)
  print("Acurácia:", acuracia)

  # Calcular o F-score
  fscore = f1_score(y_test, y_pred, average='macro')
  print("F-score:", fscore)

  # Calcular o recall
  recall = recall_score(y_test, y_pred, average='macro')
  print("Recall:", recall)

  # Realizar validação cruzada
  scores = cross_val_score(modelo_rf, x, y, cv=5)  # cv define o número de dobras (folds)
  print("Acurácia da Validação Cruzada:", np.mean(scores))

  return modelo_rf, y_test, y_pred

"""## 7.2 Balanceamento dos dados

- Aqui fazemos o balanceamento das features devido a descrepância de valores entre Neutros e Positivo, em relação aos Negativos.
"""

# Balanceamento dos dados
df_negativo = df_word2vec[df_word2vec['sentimento'] == 0]
df_positive = df_word2vec[df_word2vec['sentimento'] == 1]
df_neutral = df_word2vec[df_word2vec['sentimento'] == 2]

df_positive_resampled = resample(df_positive, replace=True, n_samples=len(df_negativo), random_state=42)
df_neutral_resampled = resample(df_neutral, replace=True, n_samples=len(df_negativo), random_state=42)

dfrnn_balanced = pd.concat([df_negativo, df_positive_resampled, df_neutral_resampled])

"""## 7.3 Separando os dados e testando o modelo

- Aqui fazemos o treinamento do modelo, separando os dados de feature e target.
- Já apresentamos os valores com as 3 principais métricas e após passar por uma validação cruzada.
"""

# Separando os dados em X e y (balanceados)
x = np.array(dfrnn_balanced.drop(['texto', 'texto_tratado', 'sentimento'], axis=1))
y = np.array(dfrnn_balanced['sentimento'])

model_rf, y_test, y_pred = classification_random_forest(x, y)

"""- Também apresentamos uma outra visualização dos resultados.
- Apresentamos o valor de cada classe perante cada métrica.
- Além disso, temos a média dos valores para as 3 métricas aplicadas.


- **OBS**: Lembrando que estamos levando em conta a métrica de Recall, pois o nosso objetivo é acertar mais negativos e abrir espaços para falsos negativos.
"""

classification = classification_report(y_test, y_pred)

print("\nRelatório de Classificação:")
print(classification)

"""## 7.4 Matriz de Confusão

- Plotando a Matriz de Confusão:
  - Vertical --> Valor verdadeiro
  - Horizontal --> Valor a ser previsto
"""

# Cálculo da matriz de confusão
cm = confusion_matrix(y_test, y_pred)

# Plot da matriz de confusão
fig, ax = plt.subplots()
im = ax.imshow(cm, interpolation='nearest', cmap=plt.cm.Blues)
ax.figure.colorbar(im, ax=ax)

# Configurações do gráfico
classes = ['Negativo', 'Positivo', 'Neutro']
ax.set(xticks=np.arange(cm.shape[1]),
       yticks=np.arange(cm.shape[0]),
       xticklabels=classes,
       yticklabels=classes,
       title='Matriz de Confusão',
       ylabel='Valor Verdadeiro',
       xlabel='Valor Previsto')

# Adiciona os valores nas células da matriz
thresh = cm.max() / 2.
for i in range(cm.shape[0]):
    for j in range(cm.shape[1]):
        ax.text(j, i, format(cm[i, j], 'd'),
                ha="center", va="center",
                color="white" if cm[i, j] > thresh else "black")

# Mostra o gráfico
plt.show()

"""## 7.5 Salvando como pkl"""

# # Salvando o modelo em um arquivo PKL
# with open('/content/drive/MyDrive/Módulo 6/projeto/modelo_rf_novo.pkl', 'wb') as arquivo:
#     pickle.dump(model_rf, arquivo)
# with open('/content/drive/MyDrive/Módulo 6/projeto/modelo_rf_novo.pkl_', 'rb') as arquivo:
#     modelo_rf = pickle.load(arquivo)

"""# 8. 💣 Aplicação do modelo"""

# Lista de frases positivas
frases = [
    "Essa comida está horrível, não consigo comer.",
    "Eu amo essa música!",
    "Que dia maravilhoso!",
    "O jantar estava delicioso!",
    "Que filme terrível, não recomendo.",
    "Não suporto esse tipo de comportamento.",
    "Estou muito feliz com o resultado. 😁",
    "Adorei o novo filme do meu ator favorito.",
    "Eu gosto do banco BTG! 😍 #btgpactual",
    "Estou decepcionado com o serviço prestado. 😢",
]

# Criando o DataFrame
dataset = pd.DataFrame({'texto': frases})
dataset

from sklearn.preprocessing import MultiLabelBinarizer

# Criar uma instância do MultiLabelBinarizer
mlb = MultiLabelBinarizer()

dataset['pipeline'] = pipeline(dataset['texto'])

df_vectorized = create_word2vec_dataframe(dataset, 'pipeline', model)

# Transformar as listas de palavras em representações binárias
pipeline_encoded = mlb.fit_transform(df_vectorized['pipeline'])

# Criar um DataFrame com as representações binárias
df_pipeline_encoded = pd.DataFrame(pipeline_encoded, columns=mlb.classes_)

# Concatenar o DataFrame codificado com o DataFrame original
df_vectorized_encoded = pd.concat([df_vectorized, df_pipeline_encoded], axis=1)

# Adiciona uma coluna para cada emoji no DataFrame
for emoji, descricao in emoji_dict.items():
    df_vectorized_encoded[descricao] = df_vectorized_encoded['texto'].apply(lambda x: verifica_emoji(x, emoji))

df_vectorized_encoded

# Realizar a predição usando os dados codificados
df_vectorized_encoded['classificacao'] = model_rf.predict(df_vectorized_encoded.iloc[:, 2:-1].values)

# Exibir o DataFrame resultante
df_vectorized_encoded

